# Generated by Django 5.2 on 2025-05-11 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CausaExterna',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Causa Externa',
                'verbose_name_plural': 'Causas Externas',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='PrestadorServicio',
            fields=[
                ('codigo_habilitacion', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('direccion', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tipo_prestador', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Prestador de Servicio',
                'verbose_name_plural': 'Prestadores de Servicio',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TipoTecnologia',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Tipo de Tecnología',
                'verbose_name_plural': 'Tipos de Tecnología',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ViaIngreso',
            fields=[
                ('codigo', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Vía de Ingreso',
                'verbose_name_plural': 'Vías de Ingreso',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticoCIE10',
            fields=[
                ('codigo', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=255)),
                ('nivel', models.IntegerField()),
                ('codigo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hijos', to='contacto_servicio.diagnosticocie10')),
            ],
            options={
                'verbose_name': 'Diagnóstico CIE-10',
                'verbose_name_plural': 'Diagnósticos CIE-10',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='ProfesionalSalud',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_documento', models.CharField(max_length=2)),
                ('numero_documento', models.CharField(max_length=20)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(blank=True, max_length=50, null=True)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('especialidad', models.CharField(max_length=100)),
                ('registro_profesional', models.CharField(max_length=50)),
                ('prestador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='profesionales', to='contacto_servicio.prestadorservicio')),
            ],
            options={
                'verbose_name': 'Profesional de Salud',
                'verbose_name_plural': 'Profesionales de Salud',
                'ordering': ['primer_apellido', 'primer_nombre'],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='ContactoServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ambito_realizacion', models.CharField(choices=[('01', 'Ambulatorio'), ('02', 'Hospitalario'), ('03', 'Urgencias'), ('04', 'Domiciliario'), ('05', 'Extramural Jornada de Salud')], max_length=2, verbose_name='Ámbito de realización')),
                ('modalidad_atencion', models.CharField(choices=[('01', 'Intramural'), ('02', 'Extramural'), ('03', 'Telemedicina')], max_length=2, verbose_name='Modalidad de atención')),
                ('tipo_atencion', models.CharField(choices=[('01', 'Consulta externa'), ('02', 'Servicio de urgencias'), ('03', 'Hospitalización'), ('04', 'Quirúrgico'), ('05', 'Atención Inmediata')], max_length=2, verbose_name='Tipo de atención')),
                ('clasificacion_triage', models.CharField(blank=True, choices=[('1', 'Triage I'), ('2', 'Triage II'), ('3', 'Triage III'), ('4', 'Triage IV'), ('5', 'Triage V')], max_length=1, null=True, verbose_name='Clasificación Triage')),
                ('tipo_diagnostico', models.CharField(choices=[('01', 'Impresión diagnóstica'), ('02', 'Confirmado nuevo'), ('03', 'Confirmado repetido')], max_length=2, verbose_name='Tipo de diagnóstico')),
                ('fecha_inicio_atencion', models.DateTimeField(verbose_name='Fecha y hora de inicio de atención')),
                ('fecha_fin_atencion', models.DateTimeField(blank=True, null=True, verbose_name='Fecha y hora de fin de atención')),
                ('codigo_tecnologia', models.CharField(blank=True, max_length=20, null=True, verbose_name='Código de tecnología')),
                ('observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('causa_externa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacto_servicio.causaexterna', verbose_name='Causa externa')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos_servicio', to='pacientes.paciente', verbose_name='Paciente')),
                ('diagnostico_principal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_servicio', to='contacto_servicio.diagnosticocie10', verbose_name='Diagnóstico principal')),
                ('prestador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_servicio', to='contacto_servicio.prestadorservicio', verbose_name='Prestador de servicio')),
                ('profesional', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='contactos_servicio', to='contacto_servicio.profesionalsalud', verbose_name='Profesional de salud')),
                ('tipo_tecnologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='contacto_servicio.tipotecnologia', verbose_name='Tipo de tecnología')),
                ('via_ingreso', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacto_servicio.viaingreso', verbose_name='Vía de ingreso')),
            ],
            options={
                'verbose_name': 'Contacto con Servicio de Salud',
                'verbose_name_plural': 'Contactos con Servicio de Salud',
                'ordering': ['-fecha_inicio_atencion'],
            },
        ),
    ]
